image: node:14.17.0

clone:
  depth: full

definitions:
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - sonar
        script:
          - pipe: sonarsource/sonarcloud-scan:1.4.0
    - step: &check-quality-gate-sonarcloud
        name: Check the Quality Gate on SonarCloud
        script:
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
    - step: &node-server-deploy
        name: Install dependencies on node server
        deployment: production
        script:
          - pipe: atlassian/rsync-deploy:0.4.4
            variables:
              USER: $USER
              SERVER: $SERVER
              SSH_PORT: $PORT
              REMOTE_PATH: $DEPLOY_PATH
              DEBUG: "true"
              LOCAL_PATH: "$BITBUCKET_CLONE_DIR/**"
          - pipe: atlassian/ssh-run:0.3.0
            variables:
              SSH_USER: $USER
              SERVER: $SERVER
              COMMAND: "cd www && npm install && pm2 start"
              DEBUG: "true"
              PORT: $PORT

pipelines:
  branches:
    master:
      - step: *node-server-deploy
